spring:
  datasource:
      url: jdbc:mysql://39.108.130.210:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: password1
mybatis:
   mapperLocations: classpath:/mapper/*.xml
